//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WallAdverts.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати своє оголошення.
        /// </summary>
        public static string AddAdvert {
            get {
                return ResourceManager.GetString("AddAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис оголошення.
        /// </summary>
        public static string AdvertDescription {
            get {
                return ResourceManager.GetString("AdvertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото оголошення.
        /// </summary>
        public static string AdvertImage {
            get {
                return ResourceManager.GetString("AdvertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва оголошення.
        /// </summary>
        public static string AdvertName {
            get {
                return ResourceManager.GetString("AdvertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизація.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата народження.
        /// </summary>
        public static string DateBirthday {
            get {
                return ResourceManager.GetString("DateBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to рррр-мм-дд.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата реєстрації.
        /// </summary>
        public static string DateRegister {
            get {
                return ResourceManager.GetString("DateRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна адреса.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть свою адресу.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть свій логін.
        /// </summary>
        public static string EnterLogin {
            get {
                return ResourceManager.GetString("EnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть свій пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ця адреса уже використовується.
        /// </summary>
        public static string ErrorEmailBusy {
            get {
                return ResourceManager.GetString("ErrorEmailBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустима довжина телефону.
        /// </summary>
        public static string ErrorLengthNumber {
            get {
                return ResourceManager.GetString("ErrorLengthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей логін вже зайнятий.
        /// </summary>
        public static string ErrorLoginBusy {
            get {
                return ResourceManager.GetString("ErrorLoginBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін повинен складатись з латинських літер(починатись обов&apos;язково з літери) та цифр, розмірністю від 4 до 20 символів.
        /// </summary>
        public static string ErrorRegExLogin {
            get {
                return ResourceManager.GetString("ErrorRegExLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер повинен складатись з цифр та не перевищувати 12 символів.
        /// </summary>
        public static string ErrorRegExNumber {
            get {
                return ResourceManager.GetString("ErrorRegExNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль повинен складатись з латинських літер та цифр, розмірністю від 6 до 18 символів.
        /// </summary>
        public static string ErrorRegExPassword {
            get {
                return ResourceManager.GetString("ErrorRegExPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це обов&apos;язкове поле!.
        /// </summary>
        public static string ErrorRequiredField {
            get {
                return ResourceManager.GetString("ErrorRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть коректну адресу.
        /// </summary>
        public static string ErrorTypeEmail {
            get {
                return ResourceManager.GetString("ErrorTypeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефону.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладено.
        /// </summary>
        public static string Posted {
            get {
                return ResourceManager.GetString("Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль в системі.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрати мову.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструватись.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити зображення профілю.
        /// </summary>
        public static string UploadImageUser {
            get {
                return ResourceManager.GetString("UploadImageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оголошення автора.
        /// </summary>
        public static string UserAdverts {
            get {
                return ResourceManager.GetString("UserAdverts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін.
        /// </summary>
        public static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувачі зможуть бачити ваш номер(необов&apos;язкове поле).
        /// </summary>
        public static string UsersCanSeeNumber {
            get {
                return ResourceManager.GetString("UsersCanSeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стіна оголошень - тебе почує кожен.
        /// </summary>
        public static string WallAdvertsName {
            get {
                return ResourceManager.GetString("WallAdvertsName", resourceCulture);
            }
        }
    }
}
